### ISSUE TITLE
Any guide to install the library?

### ISSUE THREAD

**Issue by gundamftw** [KDAB/KDSingleApplication#1]
I'm having a hard time installing the library to my project. I'm using Qt Creator and I've been following this [guide](https://wiki.qt.io/SUBDIRS_-_handling_dependencies) on the folder structure.

```
   /FooApp
   |--- subdirs.pro
   `--- src
        |
        |--- subproject1
        |    |--- subproject1.pro
        |    `--- ... (source files of app)
        |--- kdsingleapplication
        |    |--- KDSingleApplication.pri
        |    |--- common.pri
        |    |--- src
        |    |    |--- src.pro

```
And then in my subproject1.pro I included the `KDSingleApplication.pri` file
```
TEMPLATE = app
include(../kdsingleapplication/KDSingleApplication.pri)
```
And in main.cpp, I added the `#include <kdsingleapplication.h>`. But then my include on QApplication in the same file complains about "QApplication file not found". Where is the conflict?

**Comment by krf** [comment]
KDSingleApplication itself does not depend on QtWidgets where the QApplication header comes from.

You probably need a `QT += widgets` in your subdirs.pro.

Please check whether that helps.

**Comment by gundamftw** [comment]
That doesn't help. Changing the line `QT = core network` in the KDSingleApplication.pri to `QT += core network` does fixed it. But now I got error about “calling a private constructor of class QString”, it's coming from the `common.pri` but I don't know where.

**Comment by krf** [comment]
You're right wrt to your first assessment. That's a bug on our side.

Also, the defines set in common.pri ideally shouldn't affect user code, but it currently does. I'm not sure `KDSingleApplication.pri` shall be included directly by users as you're doing it here, I guess this is a question for the original author.

@dangelog Any ideas?

**Comment by dangelog** [comment]
KDSingleApplication.pri isn't meant for end users, it's meant to avoid duplication inside KDSA itself. 

I didn't bother with a full blown qmake buildsystem for KDSA because ... qmake; plus, KDSA is super small. End users on make can simply add KDSA's sources to their own build (add them to SOURCES/HEADERS, and use QtNetwork). CMake users should enjoy a better integration.

**Comment by gundamftw** [comment]
> KDSingleApplication.pri isn't meant for end users, it's meant to avoid duplication inside KDSA itself.
> 
> I didn't bother with a full blown qmake "packaging" for KDSA because ... qmake; plus, KDSA is super small. End users on qmake can simply add KDSA's sources to their own build (add them to SOURCES/HEADERS, and use QtNetwork). CMake users should enjoy a better integration.

So I simply put the source folder anywhere in my project, and then in my `subproject1.pro` add the 5 header/source files from that folder and that's it?

**Comment by dangelog** [comment]
Correct, if you're using qmake it should really be that simple. Maybe also needs a define for KDSINGLEAPPLICATION_STATIC_BUILD.

**Comment by gundamftw** [comment]
Thanks I think I'm almost there, just one last error. I did the things mentioned above, when build, I got the error `'KDSingleApplication::staticMetaObject': definition of dllimport static data member not allowed`

**Comment by gundamftw** [comment]
nvm the last post, I was defining KDSINGLEAPPLICATION_BUILD instead of KDSINGLEAPPLICATION_STATIC_BUILD in the .pro file. Now it was build and ran successfully.
