### ISSUE TITLE
Socket name without XDG_SESSION_ID

### ISSUE THREAD

**Issue by jonaski** [KDAB/KDSingleApplication#13]
In [Strawberry](https://github.com/strawberrymusicplayer/strawberry) I use a `QCoreApplication` first to check for a existing instance and in that case pass command line options, if there is a existing instance, we exit after passing command line options, otherwise continue starting a full `QApplication`, this allows us to pass command line options independent of the window session, ie.: through SSH.
For this reason I've removed `XDG_SESSION_ID` from the socket name (https://github.com/strawberrymusicplayer/strawberry/blob/6dd79d5b8f53315e57843ea5bc769d0d2bffe77b/3rdparty/kdsingleapplication/kdsingleapplication_localsocket.cpp#L57). Will you accept a PR to add an option for this? If so, should we pass this option through the constructor, or as a setter function?

**Comment by nicolasfella** [comment]
I wonder if we should check whether XDG_SESSION_ID is not empty and only add it then

**Comment by nicolasfella** [comment]
It doesn't _break_ when XDG_SESSION_ID is unset, does it?

I would be surprised if XDG_SESSION_ID is set on macOS, and as far as I can tell that code is also used there

**Comment by jonaski** [comment]
Made both user and session optional, this way you can also limit the application to one instance per machine.
Also made it only add session on Unix if XDG_SESSION_ID set.

**Comment by nicolasfella** [comment]
Thank you for your contribution, I'd say we can consider this resolved

**Comment by jonaski** [comment]
Is it possible to create a new release with the recent changes (Optional with session, etc for socket name) in not to far future?
