### ISSUE TITLE
Minor release?

### ISSUE THREAD

**Issue by P-EB** [KDAB/KDSingleApplication#28]
Hello,

Trying to package KDSingleApplication into Debian (it's now a dep for owncloud-client), I met an issue that you fixed in commit https://github.com/KDAB/KDSingleApplication/commit/250ab66f58aa37193f2e8b7814946e7a43d25cc7

Would you care doing a minor release so I can include only your code? For now I made a debian patch.

Cheers!

**Comment by jonaski** [comment]
It would be nice if the new release could include the latest commits from master including `KDSingleApplication::Options` (#16) which I added.

**Comment by winterz** [comment]
Done
1.1.0 is released
